name: "build"

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
      with:
        # Nix Flakes doesn't work on shallow clones
        fetch-depth: 0
    - uses: cachix/install-nix-action@v12
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.7.0pre20220209_52f5231/install
        extra_nix_config: |
          experimental-features = nix-command flakes
    - uses: cachix/cachix-action@v8
      with:
        name: fortuneteller2k
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    # Packages that compile like snails
    - run: git config --global init.defaultBranch main && nix build -L .#discord-openasar .#phocus .#eww .#eww-wayland .#awesome-git .#picom-git .#picom-dccsillag .#picom-pijulius .#river-git
